# Phase 1 official IRCoT config with a local HuggingFace Qwen backend.
local dataset = "hotpotqa";
local retrieval_corpus_name = "hotpotqa";
local model_name = std.extVar("MODEL");
local valid_qids = [
    "5ab92dba554299131ca422a2",
    "5a7bbc50554299042af8f7d0",
    "5add363c5542990dbb2f7dc8",
    "5a835abe5542996488c2e426",
    "5ae0185b55429942ec259c1b",
    "5a790e7855429970f5fffe3d",
    "5a754ab35542993748c89819",
    "5a89c14f5542993b751ca98a",
    "5abb14bd5542992ccd8e7f07",
    "5a89d58755429946c8d6e9d9",
    "5a88f9d55542995153361218",
    "5a90620755429933b8a20508",
    "5a77acab5542992a6e59df76",
    "5abfb3435542990832d3a1c1",
    "5a8f44ab5542992414482a25",
    "5adfad0c554299603e41835a",
    "5a7fc53555429969796c1b55",
    "5a8ed9f355429917b4a5bddd",
    "5ac2ada5554299657fa2900d",
    "5a758ea55542992db9473680",
];
local prompt_reader_args = {
    "filter_by_key_values": {
        "qid": valid_qids,
    },
    "order_by_key": "qid",
    "estimated_generation_length": 300,
    "shuffle": false,
    "model_length_limit": 8000,
    "tokenizer_model_name": model_name,
};
local bm25_retrieval_count = 6;
local rc_context_type = "gold_with_2_distractors";
local rc_qa_type = "cot";

{
    "start_state": "step_by_step_bm25_retriever",
    "end_state": "[EOQ]",
    "models": {
        "step_by_step_bm25_retriever": {
            "name": "retrieve_and_reset_paragraphs",
            "next_model": "step_by_step_cot_reasoning_gen",
            "retrieval_type": "bm25",
            "retriever_host": std.extVar("RETRIEVER_HOST"),
            "retriever_port": std.extVar("RETRIEVER_PORT"),
            "retrieval_count": bm25_retrieval_count,
            "global_max_num_paras": 15,
            "query_source": "question_or_last_generated_sentence",
            "source_corpus_name": retrieval_corpus_name,
            "document_type": "title_paragraph_text",
            "return_pids": false,
            "cumulate_titles": true,
            "end_state": "[EOQ]",
        },
        "step_by_step_cot_reasoning_gen": {
            "name": "step_by_step_cot_gen",
            "next_model": "step_by_step_exit_controller",
            "prompt_file": "prompts/"+dataset+"/"+rc_context_type+"_context_cot_qa_codex.txt",
            "question_prefix": "",
            "prompt_reader_args": prompt_reader_args,
            "generation_type": "sentences",
            "reset_queries_as_sentences": false,
            "add_context": true,
            "shuffle_paras": false,
            "terminal_return_type": null,
            "disable_exit": true,
            "end_state": "[EOQ]",
            "gen_model": "hf_local",
            "model_name": model_name,
            "model_tokens_limit": 8192,
            "max_length": 160,
            "eos_text": "\n",
            "torch_dtype": "auto",
            "device_map": "auto",
            "attn_implementation": "sdpa",
            "use_chat_template": true,
        },
        "step_by_step_exit_controller": {
            "name": "step_by_step_exit_controller",
            "next_model": "step_by_step_bm25_retriever",
            "answer_extractor_regex": ".* answer is:? (.*)\\.?",
            "answer_extractor_remove_last_fullstop": true,
            "terminal_state_next_model": "generate_main_question",
            "terminal_return_type": "pids",
            "global_max_num_paras": 15,
            "end_state": "[EOQ]",
        },
        "generate_main_question": {
            "name": "copy_question",
            "next_model": "answer_main_question",
            "eoq_after_n_calls": 1,
            "end_state": "[EOQ]",
        },
        "answer_main_question": {
            "name": "llmqa",
            "next_model": "extract_answer",
            "prompt_file": "prompts/"+dataset+"/"+rc_context_type+"_context_"+rc_qa_type+"_qa_codex.txt",
            "question_prefix": "",
            "prompt_reader_args": prompt_reader_args,
            "end_state": "[EOQ]",
            "gen_model": "hf_local",
            "model_name": model_name,
            "model_tokens_limit": 8192,
            "max_length": 200,
            "eos_text": "\n\n",
            "add_context": true,
            "torch_dtype": "auto",
            "device_map": "auto",
            "attn_implementation": "sdpa",
            "use_chat_template": true,
        },
        "extract_answer": {
            "name": "answer_extractor",
            "query_source": "last_answer",
            "regex": "(?is).*?(?:answer is:?|Answer:)\\s*(.*?)\\.?$",
            "match_all_on_failure": true,
            "remove_last_fullstop": true,
        },
    },
    "reader": {
        "name": "multi_para_rc",
        "add_paras": false,
        "add_gold_paras": false,
        "add_pinned_paras": false,
    },
    "prediction_type": "answer",
}
